### ISSUE TITLE
解码部分Base64崩溃

### ISSUE THREAD

**Issue by vickyleu** [yekq/Android_JNI_AES_128_ECB_PKCS5Padding#1]
只要运行到 return out;这里,必然崩溃
stack corruption detected: aborted
libc: Fatal signal 11 (SIGSEGV) at 0xccf00121 (code=11021382), thread 13144 

char *base64_decode(const char *data, int data_len) {
    int ret_len = (data_len / 4) * 3;
    int equal_count = 0;
    char *ret = NULL;
    char *f = NULL;
    int tmp = 0;
    int temp = 0;
    char need[3];
    int prepare = 0;
    int i = 0;
    if (*(data + data_len - 1) == '=') {
        equal_count += 1;
    }
    if (*(data + data_len - 2) == '=') {
        equal_count += 1;
    }
    if (*(data + data_len - 3) == '=') {//seems impossible
        equal_count += 1;
    }
    switch (equal_count) {
        case 0:
            ret_len += 4;//3 + 1 [1 for NULL]
            break;
        case 1:
            ret_len += 4;//Ceil((6*3)/8)+1
            break;
        case 2:
            ret_len += 3;//Ceil((6*2)/8)+1
            break;
        case 3:
            ret_len += 2;//Ceil((6*1)/8)+1
            break;
        default:
            break;
    }
    ret = (char *) malloc((size_t) ret_len);
    if (ret == NULL) {
        printf("No enough memory.\n");
        exit(0);
    }
    memset(ret, 0, (size_t) ret_len);
    f = ret;
    while (tmp < (data_len - equal_count)) {
        temp = 0;
        prepare = 0;
        memset(need, 0, 4);
        while (temp < 4) {
            if (tmp >= (data_len - equal_count)) {
                break;
            }
            prepare = (prepare << 6) | (find_pos(data[tmp]));
            temp++;
            tmp++;
        }
        prepare = prepare << ((4 - temp) * 6);
        for (i = 0; i < 3; i++) {
            if (i == temp) {
                break;
            }
            *f = (char) ((prepare >> ((2 - i) * 8)) & 0xFF);
            f++;
        }
    }
    *f = '\0';
    size_t siz = strlen(ret);
    char buf[siz];
    memset(buf,0,siz);
    sprintf(buf, "%s", ret);
    char *out = (char *) malloc(siz);
    memset(out,0,siz);
    sprintf(out, "%s", buf);
    printMsg(out);
//    free(buf);
    free(f);
    return out;
}

**Comment by vickyleu** [comment]
经测试,在cm13里面,for循环几百遍都不会崩溃,可能与系统有关

**Comment by ne1188** [comment]
It is from these two lines:

`
char need[3];
`

and later...

`
 memset(need, 0, 4);
`

An unused variable of 3 bytes gets 4 bytes memset to 0. 

In this case this bug likely has no effect, as the next variable on the stack is already set to 0 and `char need[3];` would probably be padded to 4 bytes anyway for alignment reasons.
