### ISSUE TITLE
removePKCS7Padding()函数中的纠错部分不会起作用吧？

### ISSUE THREAD

**Issue by casonyks** [yekq/Android_JNI_AES_128_ECB_PKCS5Padding#3]
您好！
请问一下：
if (!HEX[lastChar] == out[index])
{
success == 0;
}
应该改成：
if (!(HEX[lastChar] == out[index]))
{
success == 0;
}
吧？

**Comment by casonyks** [comment]
@yekq

**Comment by yekq** [comment]
@casonyks 确实没起作用。应该加上括号的

**Comment by yekq** [comment]
> 您好！ 请问一下： if (!HEX[lastChar] == out[index]) { success == 0; } 应该改成： if (!(HEX[lastChar] == out[index])) { success == 0; } 吧？

@casonyks 确实没起作用。应该加上括号的
